# Generated by Django 5.0.6 on 2024-05-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
        ('customer_site', '0001_initial'),
        ('key_word', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Key_word',
            new_name='Keyword',
        ),
    ]
