# Generated by Django 5.0.6 on 2024-05-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_word', '0002_rename_key_word_keyword'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keyword',
            table='key_word',
        ),
    ]
