# Generated by Django 5.0.6 on 2024-05-24 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_site', '0003_alter_customersite_user_id'),
        ('key_word', '0003_alter_keyword_table'),
        ('user', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='site_id',
            field=models.ForeignKey(db_column='site_id', on_delete=django.db.models.deletion.CASCADE, to='customer_site.customersite'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
