# Generated by Django 5.0.6 on 2024-05-23 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('key_word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(max_length=255, verbose_name='selector')),
                ('index', models.IntegerField(verbose_name='index')),
                ('type', models.CharField(max_length=255, verbose_name='type')),
                ('content', models.TextField(verbose_name='content')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='key_word.key_word')),
            ],
        ),
    ]
