# Generated by Django 5.0.6 on 2024-05-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='component',
            table='component',
        ),
    ]
